language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm run eslint
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  fqdn: tuthanhdelatoithuong.com
  on:
    branch: master
notifications:
  email:
    recipients:
    - tuthanhdelatoithuong@gmail.com
    on_success: change
    on_failure: always
